import type { Metadata } from 'next';
import '@/app/globals.css';
import Nav from '@/components/Nav';

import { Inter } from 'next/font/google';

const inter = Inter({ weight: ['400', '500', '600'], subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <Nav />
        {children}
      </body>
    </html>
  );
}
